name: Node.js CI

on:
  schedule:
    # every day at 2am
    - cron: "0 2 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Check for duplicate dependencies
        run: yarn dedupe --check
      - name: Audit dependencies
        run: yarn npm audit --environment production
